# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cat the Programmer
email: cat.hoanghuy@gmail.com
description:  Recent Software Engineer Graduate with more than 3 years of experience in developing web applications using various language and technologies in the industry. Proficient in using Agile and Scrum to solve problems during development processes. Experienced in developing backend application and REST API to support mobile environment.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cathoang.me" # the base hostname & protocol for your site
github_username:  hchoang

# Build settings
markdown: kramdown
