social:
- {icon: 'github', link: 'https://www.github.com/hchoang'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/hchoang/'}
- {icon: 'envelope', link: 'mailto:cat.hoanghuy@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}